In [ ]:
#python library used for working with datasets - Pandas

#Numpy - Numeric Python : mathematical operations, array objects

#data sets - collection of data that contains data specific to its category

In [ ]:
##datstructures / datatypes
#series - 1 dimensional
#dataframe - 2 dimensional (rows,columns)
#panel - 3 dimensional

In [1]:
import pandas as pd
a = [1,2,3,4,5,6]
s1 = pd.Series(a)
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [2]:
print(type(s1))

<class 'pandas.Series'>

In [3]:
series=pd.Series({"Day1":120, "Day2":100, "Day3":200})
print(series)

Day1    120
Day2    100
Day3    200
dtype: int64

In [4]:
series.loc["Day2"]+=200;
print(series)

Day1    120
Day2    300
Day3    200
dtype: int64

In [3]:
b = [1, 'a', -3.0, True] #list containing different data type of object
s2=pd.Series(b)
print(s2)

0       1
1       a
2    -3.0
3    True
dtype: object

In [ ]:
#ARRAYS - collection of elements of same data type stored at contiguous memory locations - uninterrupted sequence

In [4]:
import numpy as np
c = np.array([11,12,13,14,15,16])
print(c)

s3 = pd.Series(c)
print(s3)

[11 12 13 14 15 16]
0    11
1    12
2    13
3    14
4    15
5    16
dtype: int64

In [6]:
print(s3.index)
print(s3.values)

RangeIndex(start=0, stop=6, step=1)
[11 12 13 14 15 16]

In [7]:
s4 = pd.Series(c, index = ['a','b','c','d','e','f'])
print(s4)

a    11
b    12
c    13
d    14
e    15
f    16
dtype: int64

In [8]:
print(s4['e'])

15

In [ ]:
##DATAFRAME
###COLLECTION OF SERIES
### - has both rows and column indexes
### - representation - table of data - ordered collection of columns each can have a different value type

In [21]:
x = [[1,2], [2,3], [3,4]]
df = pd.DataFrame(x)
print(df)
print(type(df))

   0  1
0  1  2
1  2  3
2  3  4
<class 'pandas.DataFrame'>

In [5]:
import pandas as pd
data={
    "Name":["Manish", "Chetan", "Aashish", "Rohit"],
    "Roll no":[12,13,14,15]
}

df1=pd.DataFrame(data)
print(df1)

      Name  Roll no
0   Manish       12
1   Chetan       13
2  Aashish       14
3    Rohit       15

In [7]:
# Add new Column
df1["Salary"]=[1.2,2.3,4.5,67.6]
print(df1)

      Name  Roll no  Salary
0   Manish       12     1.2
1   Chetan       13     2.3
2  Aashish       14     4.5
3    Rohit       15    67.6

In [10]:
# add new Row
new_row=pd.DataFrame({"Name":["Shivam"], "Roll no":[15], "Salary":[32.3]})

df1 = pd.concat([df1, new_row])
print(df1)

      Name  Roll no  Salary
0   Manish       12     1.2
1   Chetan       13     2.3
2  Aashish       14     4.5
3    Rohit       15    67.6
0   Shivam       15    32.3

In [11]:
print(df1.loc["Manish"])

KeyError: 'Manish'

In [22]:
df.rename(columns = {0:'col1', 1:'col2'}, inplace = True)
print(df.columns)
print(df.index)

Index(['col1', 'col2'], dtype='str')
RangeIndex(start=0, stop=3, step=1)

In [23]:
df['col2']

0    2
1    3
2    4
Name: col2, dtype: int64

In [24]:
print(type(df['col2']))

<class 'pandas.Series'>

In [25]:
df1=df.copy()
print(df1)

   col1  col2
0     1     2
1     2     3
2     3     4

In [26]:
del df1['col1']

In [27]:
print(df1)

   col2
0     2
1     3
2     4

In [ ]:
## save dataframe into csv or excel file
df.to_csv('data.csv') #csv
df1.to_excel('data1.xlsx') #excel
df1.to_csv('data2.csv', index=False) #csv

In [ ]:
##DATASETS

###working with datasets
### 1. save python file
### 2. make datasets folder

data=pd.read_

In [12]:
data = pd.read_csv('/Machine Learning/Iris.csv') #(doc/pandas/datasets/filename.csv)

In [33]:
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [15]:
length= data[data["SepalWidthCm"]>4.1]
print(length)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
15  16            5.7           4.4            1.5           0.4  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa

In [16]:
length= data[data["SepalWidthCm"]==3.5]
print(length)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa

In [34]:
#extract information about the data file
# basic information of the data
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [35]:
#extracct statistical information - numerical columns
# statistical information

data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [37]:
print(data.head())  #auto starting 5
print(data.head(7)) # starting 7
print(data.tail()) # last 5
print(data.tail(2)) # last 2

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
148  Iris-virginica
149  Iris-virginica

In [17]:
print(data.mean(numeric_only =True))

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [18]:
print(data.sum(numeric_only =True))
print(data.min(numeric_only =True))
print(data.max(numeric_only =True))

Id               11325.0
SepalLengthCm      876.5
SepalWidthCm       458.1
PetalLengthCm      563.8
PetalWidthCm       179.8
dtype: float64
Id               1.0
SepalLengthCm    4.3
SepalWidthCm     2.0
PetalLengthCm    1.0
PetalWidthCm     0.1
dtype: float64
Id               150.0
SepalLengthCm      7.9
SepalWidthCm       4.4
PetalLengthCm      6.9
PetalWidthCm       2.5
dtype: float64

In [19]:
print(data["SepalLengthCm"].mean())
print(data["SepalLengthCm"].max())
print(data["SepalLengthCm"].min())

5.843333333333334
7.9
4.3

In [20]:
group = data.groupby("PetalLengthCm")
print(group["PetalWidthCm"].mean())

PetalLengthCm
1.0    0.200000
1.1    0.100000
1.2    0.200000
1.3    0.257143
1.4    0.216667
1.5    0.221429
1.6    0.285714
1.7    0.350000
1.9    0.300000
3.0    1.100000
3.3    1.000000
3.5    1.000000
3.6    1.300000
3.7    1.000000
3.8    1.100000
3.9    1.233333
4.0    1.220000
4.1    1.200000
4.2    1.325000
4.3    1.300000
4.4    1.325000
4.5    1.512500
4.6    1.400000
4.7    1.420000
4.8    1.700000
4.9    1.720000
5.0    1.775000
5.1    1.925000
5.2    2.150000
5.3    2.100000
5.4    2.200000
5.5    1.900000
5.6    2.050000
5.7    2.300000
5.8    1.866667
5.9    2.200000
6.0    2.150000
6.1    2.233333
6.3    1.800000
6.4    2.000000
6.6    2.100000
6.7    2.100000
6.9    2.300000
Name: PetalWidthCm, dtype: float64

In [38]:
for item in data.columns:
    print(item)
    
print(data.columns)
print(data.shape)

Id
SepalLengthCm
SepalWidthCm
PetalLengthCm
PetalWidthCm
Species
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')
(150, 6)

In [39]:
print(data.shape[0])
print(data.shape[1])

150
6

In [40]:
data.count()

Id               150
SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150
dtype: int64

In [41]:
data['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: str

In [42]:
data['Species'].head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: str

In [44]:
data['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [43]:
data.nunique()

Id               150
SepalLengthCm     35
SepalWidthCm      23
PetalLengthCm     43
PetalWidthCm      22
Species            3
dtype: int64

In [54]:
#rename column - SepalLengthCm to sepal_length

In [45]:
data.rename(columns = {'SepalLengthCm': 'sepal_length'}, inplace = True)

In [46]:
data.columns

Index(['Id', 'sepal_length', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [47]:
#drop column
data.drop('Id', axis = 1, inplace = True) #not inplace

print(data.head(4))

   sepal_length  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa

In [27]:
data=data.drop(columns=["PetalLengthCm","Species"])
# data = data.drop(columns=["PetalLengthCm", "Species"])
print(data.head())

KeyError: "['PetalLengthCm', 'Species'] not found in axis"

In [28]:
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm
0   1            5.1           3.5           0.2
1   2            4.9           3.0           0.2
2   3            4.7           3.2           0.2
3   4            4.6           3.1           0.2
4   5            5.0           3.6           0.2

In [49]:
#drop row
data.drop(1, axis = 0) #drops row 1 - not inplace

# print(data.head(4))

     sepal_length  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0             5.1           3.5            1.4           0.2     Iris-setosa
2             4.7           3.2            1.3           0.2     Iris-setosa
3             4.6           3.1            1.5           0.2     Iris-setosa
4             5.0           3.6            1.4           0.2     Iris-setosa
5             5.4           3.9            1.7           0.4     Iris-setosa
..            ...           ...            ...           ...             ...
145           6.7           3.0            5.2           2.3  Iris-virginica
146           6.3           2.5            5.0           1.9  Iris-virginica
147           6.5           3.0            5.2           2.0  Iris-virginica
148           6.2           3.4            5.4           2.3  Iris-virginica
149           5.9           3.0            5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [50]:
print(data.head(5))

   sepal_length  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa
4           5.0           3.6            1.4           0.2  Iris-setosa

In [51]:
data.isnull()

     sepal_length  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0           False         False          False         False    False
1           False         False          False         False    False
2           False         False          False         False    False
3           False         False          False         False    False
4           False         False          False         False    False
..            ...           ...            ...           ...      ...
145         False         False          False         False    False
146         False         False          False         False    False
147         False         False          False         False    False
148         False         False          False         False    False
149         False         False          False         False    False

[150 rows x 5 columns]

In [52]:
data.isnull().sum() #sum() - provide a count of NaN values per column

sepal_length     0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [53]:
#handling missing values
# 1. drop , 2. fill
# data.dropna() - drop all null values from a row - NOT INPLACE
# drop all null values from col - data.dropna(axis = 1)
##parameter - any, all
  ### data.dropna(how = 'all') - will drop if all values are null, any: will drop if any value is null

In [ ]:
# fillna( ) - NOT INPLACE
##data.fillna(value) , value - scalar, dict, series, df, can not be a list
    ###data['sepal_length'].fillna(data['sepal_length'].mean())
    ###data['sepal_length'].fillna(method = 'bfill')
#parameters
  ## axis
  ## method - backfill, bfill, pad, ffill, none -
    ### pad/ffill - propogates the last valid observation
    ### bfill/backfill - use the next valid observation

In [55]:
#interpolate(method = '')
  ##fills missing values by estimating them using interpolation techniques like linear, polynomial, etc.
    ##Uses the trend or pattern of data to estimate missing values., s useful for numerical or time-series data,
    ##Provides smoother, more accurate fills for graphs, analysis, or machine learning.

| Method                 | Description                           | Example                      |
| ---------------------- | ------------------------------------- | ---------------------------- |
| `'linear'` *(default)* | Linearly estimates between two values | Good for even time/data      |
| `'time'`               | Interpolates using time-based index   | Use when index is `datetime` |
| `'polynomial'`         | Fits a polynomial curve               | Use `order=` with it         |
| `'spline'`             | Smooth interpolation like a curve     | Needs SciPy                  |
| `'nearest'`            | Takes nearest known value             | Like rounding                |

In [ ]:
#data['column name'].interpolate(limit=1) → limit - max num of consecutive values to be filled

What does order do?
It specifies the degree of the polynomial used for interpolation.

Higher order = more complex curve.

Lower order = simpler curve (like a straight line if order=1).

| `order` | Curve Type               | Use Case                                 |
| ------- | ------------------------ | ---------------------------------------- |
| 1       | Linear                   | Simple trends                            |
| 2       | Quadratic                | Slight curves                            |
| 3+      | Polynomial (cubic, etc.) | More complex patterns (e.g. time series) |

In [71]:
import pandas as pd
import numpy as np

# Create DataFrame with NaN values
Data = {
    'Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Sales': [200, np.nan, 250, np.nan, 300]
}

df = pd.DataFrame(Data)

print("Original Data:")
print(df)

Original Data:
   Day  Sales
0  Mon  200.0
1  Tue    NaN
2  Wed  250.0
3  Thu    NaN
4  Fri  300.0

In [57]:
df.isnull()

     Day  Sales
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False

In [58]:
df.isnull().sum()

Day      0
Sales    2
dtype: int64

In [59]:
df.dropna()

   Day  Sales
0  Mon  200.0
2  Wed  250.0
4  Fri  300.0

In [60]:
df

   Day  Sales
0  Mon  200.0
1  Tue    NaN
2  Wed  250.0
3  Thu    NaN
4  Fri  300.0

In [61]:
df.fillna(value=0)

   Day  Sales
0  Mon  200.0
1  Tue    0.0
2  Wed  250.0
3  Thu    0.0
4  Fri  300.0

In [63]:
# df.fillna(method='bfill') old version
df.bfill()

   Day  Sales
0  Mon  200.0
1  Tue  250.0
2  Wed  250.0
3  Thu  300.0
4  Fri  300.0

In [64]:
df.ffill()

   Day  Sales
0  Mon  200.0
1  Tue  200.0
2  Wed  250.0
3  Thu  250.0
4  Fri  300.0

In [65]:
df.fillna('null_value')

   Day       Sales
0  Mon       200.0
1  Tue  null_value
2  Wed       250.0
3  Thu  null_value
4  Fri       300.0

In [66]:
df['Sales'].mean()

np.float64(250.0)

In [67]:
df.fillna(df['Sales'].mean())

   Day  Sales
0  Mon  200.0
1  Tue  250.0
2  Wed  250.0
3  Thu  250.0
4  Fri  300.0

In [72]:
#interpolate
# df.interpolate() only works on numeric data, but your DataFrame contains string (object) values.
df.interpolate() #default - method = linear

TypeError: Cannot interpolate with str dtype

In [70]:
df.interpolate(method='nearest')

TypeError: Cannot interpolate with str dtype

In [ ]:
df.interpolate(method='polynomial', order=1)

In [29]:
data["PetalWidthCm"]= data["PetalWidthCm"].replace({0.2:0.4})

In [30]:
# updated data printed
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm
0   1            5.1           3.5           0.4
1   2            4.9           3.0           0.4
2   3            4.7           3.2           0.4
3   4            4.6           3.1           0.4
4   5            5.0           3.6           0.4

In [74]:
dates = pd.date_range(start='2025-06-01', periods=5, freq='D')
sales = [200, np.nan, 250, np.nan, 300]
dates

DatetimeIndex(['2025-06-01', '2025-06-02', '2025-06-03', '2025-06-04',
               '2025-06-05'],
              dtype='datetime64[us]', freq='D')

In [75]:
df =pd.DataFrame({'Sales':sales},index=dates)
print(df)

            Sales
2025-06-01  200.0
2025-06-02    NaN
2025-06-03  250.0
2025-06-04    NaN
2025-06-05  300.0

In [76]:
df.interpolate(method='time')

            Sales
2025-06-01  200.0
2025-06-02  225.0
2025-06-03  250.0
2025-06-04  275.0
2025-06-05  300.0

In [ ]:
#date_range - range of dates at a specified frequency.
#pd.date_range(start=None, end=None, periods=None, freq='D')

What does order do?
It specifies the degree of the polynomial used for interpolation.

Higher order = more complex curve.

Lower order = simpler curve (like a straight line if order=1).

| `order` | Curve Type               | Use Case                                 |
| ------- | ------------------------ | ---------------------------------------- |
| 1       | Linear                   | Simple trends                            |
| 2       | Quadratic                | Slight curves                            |
| 3+      | Polynomial (cubic, etc.) | More complex patterns (e.g. time series) |

In [77]:
#Generate 5 dates from a start date:
d = pd.date_range(start='2025-12-01', periods=5)
print(d)

DatetimeIndex(['2025-12-01', '2025-12-02', '2025-12-03', '2025-12-04',
               '2025-12-05'],
              dtype='datetime64[us]', freq='D')

In [78]:
pd.date_range(start='2025-01-01', end='2025-01-12')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12'],
              dtype='datetime64[us]', freq='D')

| Code  | Meaning                     |
| ----- | --------------------------- |
| `'D'` | Daily                       |
| `'H'` | Hourly                      |
| `'ME'` | Month end                   |
| `'W'` | Weekly                      |
| `'YE'` | Year end                    |
| `'B'` | Business Day (Mon–Fri only) |

In [79]:
pd.date_range(start='2025-06-01', periods=4, freq='h') #hourly range

DatetimeIndex(['2025-06-01 00:00:00', '2025-06-01 01:00:00',
               '2025-06-01 02:00:00', '2025-06-01 03:00:00'],
              dtype='datetime64[us]', freq='h')

In [80]:
pd.date_range(start='2025-06-19', periods=7, freq='B')

DatetimeIndex(['2025-06-19', '2025-06-20', '2025-06-23', '2025-06-24',
               '2025-06-25', '2025-06-26', '2025-06-27'],
              dtype='datetime64[us]', freq='B')

In [81]:
pd.date_range(start='2025-06-19', periods=7, freq='ME')

DatetimeIndex(['2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30',
               '2025-10-31', '2025-11-30', '2025-12-31'],
              dtype='datetime64[us]', freq='ME')

In [82]:
pd.date_range(start='2025-09-19', periods=7, freq='ME')

DatetimeIndex(['2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31'],
              dtype='datetime64[us]', freq='ME')

In [83]:
pd.date_range(start='2025-06-19', periods=7, freq='W')

DatetimeIndex(['2025-06-22', '2025-06-29', '2025-07-06', '2025-07-13',
               '2025-07-20', '2025-07-27', '2025-08-03'],
              dtype='datetime64[us]', freq='W-SUN')

In [84]:
pd.date_range(start='2025-06-19', periods=7, freq='W-FRI')

DatetimeIndex(['2025-06-20', '2025-06-27', '2025-07-04', '2025-07-11',
               '2025-07-18', '2025-07-25', '2025-08-01'],
              dtype='datetime64[us]', freq='W-FRI')

In [85]:
pd.date_range(start='2025-06-19', periods=7, freq='YE')

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [86]:
pd.date_range(start='2025-06-19', periods=7, freq='YE-MAR')

DatetimeIndex(['2026-03-31', '2027-03-31', '2028-03-31', '2029-03-31',
               '2030-03-31', '2031-03-31', '2032-03-31'],
              dtype='datetime64[us]', freq='YE-MAR')

In [87]:
## handling duplicates  - NOT INPLACE
  #data.drop_duplicates() - Removes duplicate rows based on all col
  ## data.drop_duplicates(subset=['sepal_length'])

  #parameters
    ##keep - first(default)[keeps first], last[keeps last], false[remove all]
    ##ignore_index = false[Keeps the original index], true[Resets the index to start from 0, 1, 2...]

In [88]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30]
})
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2    Alice   25
3  Charlie   35
4      Bob   30

In [89]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [90]:
df1 = df.copy()

In [91]:
df.drop_duplicates(keep= 'first', ignore_index=True)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [92]:
df.drop_duplicates(keep='last', ignore_index=False)

      Name  Age
2    Alice   25
3  Charlie   35
4      Bob   30

In [ ]:
# How many missing values are there in each column of a dataset?
#Display all rows where a specific column (e.g., age) has missing values.
#Drop rows with any missing values from the dataset.
#Drop columns with more than 50% missing data.

In [93]:
# Numpy

In [94]:
import numpy as np
p = np.array([1,2,3,4,5])

#randomly genenrated array
q = np.random.rand(5) #5 = columns (1 - dimensional)
print(q)

[0.51604694 0.39917913 0.0760037  0.2996404  0.41175202]

In [95]:
r = np.random.rand(4,5) #4 rows, 5 columns
print(r)

[[0.53816255 0.31791271 0.63119189 0.29283601 0.70836177]
 [0.89986344 0.02449081 0.54504745 0.1297321  0.90199679]
 [0.83654098 0.09724712 0.48332529 0.42598897 0.64236693]
 [0.90586662 0.3063735  0.27531033 0.25484841 0.5203113 ]]

In [96]:
type(r)

numpy.ndarray

In [97]:
df = pd.read_csv('/Machine Learning/Iris.csv')
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [98]:
df.loc[7:10]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa

In [99]:
df.iloc[:10]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [100]:
df.iloc[40:45]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa

In [ ]:
#loc - label indixing, uses name
#iloc - integer based indexing, uses numbers

In [101]:
df.loc[20:30, 'SepalLengthCm'] #check for mentioned col

20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
30    4.8
Name: SepalLengthCm, dtype: float64

In [102]:
df.loc[20:30, ['SepalLengthCm', 'SepalWidthCm']]

    SepalLengthCm  SepalWidthCm
20            5.4           3.4
21            5.1           3.7
22            4.6           3.6
23            5.1           3.3
24            4.8           3.4
25            5.0           3.0
26            5.0           3.4
27            5.2           3.5
28            5.2           3.4
29            4.7           3.2
30            4.8           3.1

In [ ]:
#col name - col index

In [103]:
df.iloc[20:30, 1]

20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
Name: SepalLengthCm, dtype: float64

In [104]:
df.iloc[20:30, [1,3]]

    SepalLengthCm  PetalLengthCm
20            5.4            1.7
21            5.1            1.5
22            4.6            1.0
23            5.1            1.7
24            4.8            1.9
25            5.0            1.6
26            5.0            1.6
27            5.2            1.5
28            5.2            1.4
29            4.7            1.6

In [105]:
##col - accesed by indexes not name

In [106]:
#access all rows for all col
df.loc[:]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [107]:
##boolean indexing
print(df.iloc[20:30, [1,3]].mean())

SepalLengthCm    5.01
PetalLengthCm    1.55
dtype: float64

In [108]:
df['SepalLengthCm'].mean()

np.float64(5.843333333333334)

In [109]:
z = df.iloc[20:30, 1] > df['SepalLengthCm'].mean()
print(z)

20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: SepalLengthCm, dtype: bool

In [110]:
x = df.iloc[140:, 1] > df['SepalLengthCm'].mean()
print(x)

140     True
141     True
142    False
143     True
144     True
145     True
146     True
147     True
148     True
149     True
Name: SepalLengthCm, dtype: bool

In [111]:
df.loc[5, 'SepalLengthCm']

np.float64(5.4)

In [112]:
df1 = df.copy()
df1.loc[5, 'SepalLengthCm'] = 10
df1.loc[5, 'SepalLengthCm']

np.float64(10.0)

In [113]:
#transposing
#rows - columns

df.T # not inplace

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
Id,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [114]:
## add column to data
df.loc[:,'rank']='high'
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,rank
0,1,5.1,3.5,1.4,0.2,Iris-setosa,high
1,2,4.9,3.0,1.4,0.2,Iris-setosa,high
2,3,4.7,3.2,1.3,0.2,Iris-setosa,high
3,4,4.6,3.1,1.5,0.2,Iris-setosa,high
4,5,5.0,3.6,1.4,0.2,Iris-setosa,high
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,high
146,147,6.3,2.5,5.0,1.9,Iris-virginica,high
147,148,6.5,3.0,5.2,2.0,Iris-virginica,high
148,149,6.2,3.4,5.4,2.3,Iris-virginica,high
149,150,5.9,3.0,5.1,1.8,Iris-virginica,high

In [115]:
df.loc[0:10, 'rank']='med'
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,rank
0,1,5.1,3.5,1.4,0.2,Iris-setosa,med
1,2,4.9,3.0,1.4,0.2,Iris-setosa,med
2,3,4.7,3.2,1.3,0.2,Iris-setosa,med
3,4,4.6,3.1,1.5,0.2,Iris-setosa,med
4,5,5.0,3.6,1.4,0.2,Iris-setosa,med
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,high
146,147,6.3,2.5,5.0,1.9,Iris-virginica,high
147,148,6.5,3.0,5.2,2.0,Iris-virginica,high
148,149,6.2,3.4,5.4,2.3,Iris-virginica,high
149,150,5.9,3.0,5.1,1.8,Iris-virginica,high

In [116]:
df.loc[2:5,'country']='India'
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,rank,country
0,1,5.1,3.5,1.4,0.2,Iris-setosa,med,NaN
1,2,4.9,3.0,1.4,0.2,Iris-setosa,med,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa,med,India
3,4,4.6,3.1,1.5,0.2,Iris-setosa,med,India
4,5,5.0,3.6,1.4,0.2,Iris-setosa,med,India
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,high,NaN
146,147,6.3,2.5,5.0,1.9,Iris-virginica,high,NaN
147,148,6.5,3.0,5.2,2.0,Iris-virginica,high,NaN
148,149,6.2,3.4,5.4,2.3,Iris-virginica,high,NaN
149,150,5.9,3.0,5.1,1.8,Iris-virginica,high,NaN

In [ ]:
#row - 2 to 5 , col name - country , value - india

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
 6   rank           150 non-null    str
 7   country        4 non-null      str
dtypes: float64(4), int64(1), str(3)
memory usage: 9.5 KB

In [118]:
df.astype({'SepalLengthCm' : 'int'})

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,rank,country
0,1,5,3.5,1.4,0.2,Iris-setosa,med,NaN
1,2,4,3.0,1.4,0.2,Iris-setosa,med,NaN
2,3,4,3.2,1.3,0.2,Iris-setosa,med,India
3,4,4,3.1,1.5,0.2,Iris-setosa,med,India
4,5,5,3.6,1.4,0.2,Iris-setosa,med,India
...,...,...,...,...,...,...,...,...
145,146,6,3.0,5.2,2.3,Iris-virginica,high,NaN
146,147,6,2.5,5.0,1.9,Iris-virginica,high,NaN
147,148,6,3.0,5.2,2.0,Iris-virginica,high,NaN
148,149,6,3.4,5.4,2.3,Iris-virginica,high,NaN
149,150,5,3.0,5.1,1.8,Iris-virginica,high,NaN

In [119]:
df =df['SepalWidthCm'].astype('int')

In [120]:
df.dtypes

dtype('int64')